### ISSUE TITLE
Posting: Embedded YouTube Video won't show up when posted

### ISSUE THREAD

**Issue by cyboryan** [ssarljames/portal#2]
![image](https://user-images.githubusercontent.com/32955000/83086579-bc822700-a0c1-11ea-8528-948fa9be788f.png)
![image](https://user-images.githubusercontent.com/32955000/83086592-c6a42580-a0c1-11ea-816a-15e8822d6759.png)

**Comment by ssarljames** [comment]
Please file issues [here](https://github.com/cs-cube/portal-frontend)

Making this private repo for deployment purposes only.

**Comment by cyboryan** [comment]
Will re-issue this to the link you provided. Thanks ;)
